<?php echo $this->qu_admin_navigation('qu_admin_navigation');  ?>

<!-- DISQUS
<div class="container">
    <div class="row">
        <div class="span12">
            <div id="disqus_thread"  style="margin:60px 25px 60px 40px"></div>
            <script type="text/javascript">
                var disqus_shortname = 'qumodules';
                (function() {
                    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                })();
            </script>
        </div>
    </div>
</div>-->