<?php
$baseUrl = $this->placeholder('urlPage');
if($this->pageCount){
    ?>
    <div class="pagination pull-right">
        <ul>
            <? if(isset($this->previous)){?>
                <li><a href="<?=$baseUrl; ?>?page=<?=$this->first; ?>"><span class="iconb" data-icon="&#xe24f;"></span></a></li>
                <li><a href="<?=$baseUrl; ?>?page=<?=$this->previous; ?>"><span class="iconb" data-icon="&#xe24b;"></span></a></li>
            <? } ?>
            <? foreach($this->pagesInRange as $page){ ?>
                <li<? if($page == $this->current){ echo ' class="active"'; } ?>>
                    <a href="<?=$baseUrl; ?>?page=<?=$page; ?>"><?=$page; ?></a>
                </li>
            <? } ?>
            <? if(isset($this->next)){ ?>
                <li><a href="<?=$baseUrl; ?>?page=<?=$this->next; ?>"><span class="iconb" data-icon="&#xe24e;"></span></a></li>
                <li><a href="<?=$baseUrl; ?>?page=<?=$this->last; ?>"><span class="iconb" data-icon="&#xe252;"></span></a></li>
            <? } ?>
        </ul>
        <div class="pagination-label">
          <label>Showing <?=$this->firstItemNumber?> to <?=$this->lastItemNumber?> of  <?=$this->totalItemCount?> records</label>
        </div>
    </div>


<? }