
<form action="<?php echo $this->url($route,array('lang'=>$this->lang,'model'=>$model,'action'=>'delete','id'=>$id))?>" method="post" id="form">


    <div class="nav-actions-absolute">
        <div class="nav-actions">
            <div class="title-nav">
                Delete records
            </div>
            <div class="buttons-nav">
                <input class="btn  btn-danger"  data-icon="&#xe0c8;" style="margin:3px 3px 0 0;"   value="Delete" name="delete" type="submit">
                <input class="btn  btn-inverse"  style="margin:3px 3px 0 0;"    value="Cançelar" name="cancel"  type="submit">
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="nav-actions-height"></div>

    <div class="form row-fluid check check-duplicate-delete">

        <fieldset class="formBlock check-duplicate-delete-all">
            <input type="checkbox" id="titleCheck" name="titleCheck" />  <label for="titleCheck"><span class="title-check">Check all</span></label>
        </fieldset>

        <div class="fromIn" id="checkAll">

            <? foreach($Delete as $d){  ?>
                <fieldset class="formBlock">

                    <?php if($d[$key['Title']]){  $title = $d[$key['Title']];
                    }else{  $title = '<span class="Unnamed">Unnamed</span>'; }  ?>

                    <legend>
                        <label for="lab-<?php echo $d[$key['Id']]; ?>">
                            <input type="checkbox" id="lab-<?php echo $d[$key['Id']]; ?>" name="checkRow[]" value="<?php echo $d[$key['Id']]; ?>"/>
                            <span class="title-check"><?php echo $title; ?></span>
                        </label>
                    </legend>

                    <? if( $this->qu_admin_map($d[$key['Id']],$options,$model,$route,$lang)){ ?>

                        <div class="row-fluid">
                            <div class="span12">
                                <?php $this->qu_admin_map($d[$key['Id']],$options,$model,$route,$lang); ?>
                            </div>
                        </div>

                    <? } ?>

                </fieldset>
            <? } ?>

        </div>
    </div>
</form>
<script>
    $("#titleCheck").click(function() {
        var checkedStatus = this.checked;
        $("#checkAll").find("input:checkbox").each(function() {
            this.checked = checkedStatus;
            if (checkedStatus == this.checked) {
                $(this).closest('.checker > span').removeClass('checked');
                $(this).closest('table tbody tr').removeClass('thisRow');
            }
            if (this.checked) {
                $(this).closest('.checker > span').addClass('checked');
                $(this).closest('table tbody tr').addClass('thisRow');
            }
        });
    });

    $(function() {
        $('#checkAll').find('input[type=checkbox]').change(function() {
            $(this).closest('tr').toggleClass("thisRow", this.checked);
        });

    });
</script>
