<?php $cols = 2; ?>
<form method="post" id="form">
    <table cellpadding="0" cellspacing="0" width="100%" class="table tMedia  table-bordered table-striped" id="checkAll">
        <thead>
        <tr>
            <td width="30" class="tableArrows"><img src="<?php echo $this->basePath(); ?>/img/tableArrows.png" alt="" /></td>

            <?php if($key['Order']){ $cols += 1; ?>
                <td width="30" class="tableArrows"><div class="iconb" data-icon="&#xe152;"></div></td>
            <?php } ?>

            <?php if($key['Icon']){   $cols += 1; ?>
                <td width="20">Icon</td>
            <?php } ?>

            <?php if($options->getDocuments()){  $cols += 1; ?>
                <td width="35">Imatge</td>
            <?php } ?>

            <?php if($key['Title']){   $cols += 1; ?>
                <td><div>Title<span></span></div></td>
            <?php } ?>

            <?php if($key['Name']){   $cols += 1; ?>
                <td width="100"><div>Name<span></span></div></td>
            <?php } ?>

            <?php if($key['Modified']){   $cols += 1; ?>
                <td  width="80"><div>Data<span></span></div></td>
            <?php } ?>

            <?php if($key['IdAuthor']){ $cols += 1; ?>
                <td  width="50"><div>Autor<span></span></div></td>
            <?php } ?>

            <?php if($key['Order']){ $cols += 1; ?>
                <td  width="30"><div>Or.<span></span></div></td>
            <?php } ?>

            <?php  if($key['Lang']){ $cols += 1; ?>
                <td  width="125"><div>Lang<span></span></div></td>
            <?php } ?>

            <?php if($key['Status']){ $cols += 1; ?>
                <td  width="47"><div>Status<span></span></div></td>
            <?php } ?>

            <td width="70">Actions</td>


            <?php if($options->getLinkerParent() > $level){ $cols += 1; ?>

                <td  width="80">
                    <div>Children<span></span></div>
                </td>

            <?php } ?>

            <?php

                $LinkerModels = $options->getLinkerModels();

                if(count($LinkerModels)){
                    foreach($LinkerModels as $LinkerModel){  $cols += 1;

                        if($LinkerModel['level'] === true){
                            $cols += 1;?>
                            <td  width="80">
                                <div><?php echo $LinkerModel['name'] ?><span></span></div>
                            </td>

            <?php      }elseif($LinkerModel['level'] == $level){  $cols += 1; ?>

                            <td  width="80">
                                <div><?php echo $LinkerModel['name'] ?><span></span></div>
                            </td>
           <?php        }
                    }
                }
            ?>

        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="<?php echo  $cols; ?>">
                <div class="pull-left">
                    <select  name="action" class="btn AjaxOptions" style="width:130px;" id="action" onchange="this.form.submit($('form').attr('action', '<? echo $this->url($route,array('lang'=>$lang));  ?>/' + $(this).val() + '/<?php if($model) echo $model.'/'; ?><?php echo $id?>'))">
                        <option value="">Select option</option>
                        <option value="duplicate">Duplicate</option>
                        <option value="delete">Delete</option>
                    </select>
                </div>
                <? $this->placeholder('urlPage')->set($this->url($route,array('action'=>'qu_admin_table_ajax','model'=>$model,'lang'=>$lang,'id' => $id))); ?>
                <?php echo $this->paginationControl($this->list, 'Sliding', 'qu-admin/layout/pagination'); ?>

            </td>
        </tr>
        </tfoot>
        <tbody>
        <?php
        if(!0 == count($this->list)){
            foreach($this->list as $list){
                if($key['IdLang'] and $key['Lang']){

                    $id_list = $list[$key['IdLang']];
                    $qu_admin_lang_nav_table = $this->qu_admin_lang_nav_table($id_list,$list[$key['Lang']],$options,$route,$model,$id);

                }else{

                    $id_list = $list[$key['Id']];
                    $qu_admin_lang_nav_table = $this->qu_admin_lang_nav_table($id_list,null,$options,$route,$model,$id);
                }

                ?>
                <tr id="item_<?php echo $list[$key['Id']]; ?>" char="<?php echo $list[$key['Order']]; ?>">

                    <td class="center">
                        <input type="checkbox" name="checkRow[]" value="<?php echo $id_list?>"/>
                    </td>

                    <?php if($key['Order']){  ?>
                        <td class="handle tableArrows center">
                            <span class="iconb" data-icon="&#xe152;" style="font-size:17px; color:#999;"></span>
                        </td>
                    <?php } ?>

                    <?php if($key['Icon']){ ?>
                        <td class="center iconb-view">
                            <?php echo $list[$key['Icon']];?>
                        </td>
                    <?php } ?>

                    <?php if($options->getDocuments()){  ?>
                        <td class="center">
                            <?php echo $this->qu_admin_documents($id_list,$options); ?>
                        </td>
                    <?php } ?>

                    <?php if($key['Title']){  ?>
                        <td>
                            <div  style="height:20px; overflow:hidden;">
                                <?php echo $list[$key['Title']];?>
                            </div>
                        </td>
                    <?php } ?>

                    <?php if($key['Name']){ ?>
                        <td>
                            <div  style="height:20px; overflow:hidden;">
                                <?php echo $list[$key['Name']];?>
                            </div>
                        </td>
                    <?php } ?>

                    <?php if($key['Modified']){ ?>
                        <td class="center">
                            <?php  echo strftime("%d/%m/%Y", strtotime($list[$key['Modified']]));?>
                        </td>
                    <?php } ?>

                    <?php if($key['IdAuthor']){ $cols += 1; ?>
                        <td class="center">
                            <?php echo $this->qu_admin_user_name($list[$key['IdAuthor']]); ?>
                        </td>
                    <?php } ?>

                    <?php if($key['Order']){ $cols += 1; ?>
                        <td class="center">
                            <?php echo $list[$key['Order']];?>
                        </td>
                    <?php } ?>

                    <?php  if($key['Lang']){  ?>
                        <?php echo $qu_admin_lang_nav_table->getNavMenuTd(); ?>
                    <?php } ?>

                    <?php if($key['Status']){ ?>
                        <td class="center">
                            <a href="<?php echo $this->url($route,array('lang'=>$lang,'action'=>'edit','model'=>$model, 'id' => $id_list ));?>">
                                <?php echo $this->qu_admin_status($list[$key['Status']]); ?>
                            </a>
                        </td>
                    <?php } ?>


                    <td class="tableActs">
                        <div class="pagination-centered ">
                       <div class="btn-group dropup">
                            <button class="btn css-dropdown" data-toggle="dropdown">
                                <span class="iconb" data-icon="&#xe04d;"></span>
                            </button>
                            <ul class="dropdown-menu pull-right">
                                <?php echo $qu_admin_lang_nav_table->getNavMenuLi(); ?>
                                <li><a href="<?php echo $this->url($route,array('lang'=>$lang,'model'=>$model,'action'=>'duplicate','id'=>$list[$key['IdParent']],'id_parent'=>$list[$key['Id']]));?>"><span class="icon-copy"></span>Duplicate</a></li>
                                <li><a href="<?php echo $this->url($route,array('lang'=>$lang,'model'=>$model,'action'=>'delete','id'=>$list[$key['IdParent']],'id_parent'=>$list[$key['Id']]));?>"><span class="icon-remove-2"></span>Delete</a></li>
                            </ul>
                       </div>
                            <a href="<?php echo $this->url($route,array('lang'=>$lang,'model'=>$model,'action'=>'edit', 'id' => $id_list ));?>" class="btn btn-small" title="Edit"><span class="iconb" data-icon="&#xe1db;"></span></a>

                        </div>
                    </td>


                  <?php if($options->getLinkerParent() > $level){ ?>
                      <?php echo $qu_admin_lang_nav_table->getCountChild();?>
                  <?php } ?>

                    <?php echo $qu_admin_lang_nav_table->getLinkModel();?>


                </tr>
            <? } } ?>
        </tbody>
    </table>
</form>
<? if(isset($ajax)){ ?>
    <script type="text/javascript">
        $("select").chosen({width:"95%"});
    </script>
<? } ?>
<script type="text/javascript">


    var UrlAdmin = '<?php echo $this->url($route,array('action'=>'qu_admin_table_ajax', 'model'=>$model, 'id' => $id,'lang'=>$lang));?>';
    var NumPerPage = '<?php echo $npp; ?>';
    var Search = encodeURIComponent('<?php echo $q?>');
    var Page = '<?php echo $page ?>';
    var id = '<?php echo $id ?>';
    var Lang = '<?php echo $lang ?>';
    var ajax = $('#ajax');
    var checkAll =  $('#checkAll').find('tbody tr').attr('char');


    function NumPage() {

        $('.headLoad').css('display','block');
        ajax.load(UrlAdmin + '?q=' +  Search + '&npp=' + $("#npp").val() + '&page=' + Page, function(){
            $('.headLoad').css('display','none');
            ajax.find('select').uniform();
            ajax.find('input:checkbox').uniform();
            initTable();
        });
    }

    $(".pagination a").click(function(){

        var href = $(this).attr('href');
        $('.headLoad').css('display','block');
        ajax.load(href  + '&q=' + Search + '&npp=' + NumPerPage   ,function(){
            $('.headLoad').css('display','none');
            ajax.find('select').uniform();
            ajax.find('input:checkbox').uniform();
            initTable();
        });
        return false;
    });


    function search()
    {

        var valor = $('#q').val();


        $('.headLoad').css('display','block');
        ajax.load(UrlAdmin + '?q=' + encodeURIComponent(valor) + '&npp=' + NumPerPage + '&page=' + Page , function(){
            $('.headLoad').css('display','none');
            ajax.find('select').uniform();
            ajax.find('input:checkbox').uniform();
            initTable();
        });
    }


    Sort();
    function Sort(){

        var fixHelperModified = function(e, tr) {
            var $originals = tr.children();
            var $helper = tr.clone();
            $helper.children().each(function(index)
            {
                $(this).width($originals.eq(index).width())
            });
            return $helper;
        };
        $("tbody").sortable({

            helper:fixHelperModified,
            opacity: 0.6,
            handle: ".handle",

            start: function(e, ui){
                ui.placeholder.height(ui.item.height()+1);
            },

            stop:function (e) {

                var order = $('#checkAll').find('tbody').sortable('serialize');

                $('.headLoad').css('display','block');
                ajax.load( UrlAdmin + "?" + order + '&n=' + checkAll + '&npp=' + NumPerPage + '&page=' + Page, function(){
                    $('.headLoad').css('display','none');
                    ajax.find('select').uniform();
                    ajax.find('input:checkbox').uniform();
                    initTable();
                });
            }
        }).disableSelection();
    }


</script>