<?php

echo $this->qu_admin_bread_crumb($options,$id,$route,$lang,$model,$this->mergeBreadCrumbModels);
$form = $this->form;
$form->setAttribute('action',$this->url($route ,array('action' => $action,'model' => $model,'id'=>$id,'lang'=>$lang)));
$form->setAttribute('enctype', 'multipart/form-data');
$form->setAttribute('id', $action);
$form->prepare();
echo $this->form()->openTag($form) . PHP_EOL;
//echo $this->formElement($form->get('csrf'));

?>


    <div class="nav-actions-absolute">
        <div class="nav-actions">
            <?php echo $this->qu_admin_title_by_db($options,$key,$route,$model,$action); ?>
            <?php echo $this->qu_admin_add($route,$id,$lang,$options,$action,$model); ?>
            <?php echo $this->qu_admin_languages($options,$route,$lang,$action,$id,$model); ?>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="nav-actions-height"></div>

<?php if(isset($dataDb['numero_sortida'])){ ?>


    <style>
        .table-striped tbody>tr:nth-child(odd)>td, .table-striped tbody>tr:nth-child(odd)>th {
            background-color: #E4E4E4;
        }

        .title-nav,
        .sidebar,
        .crumb,
        .breadcrumbs,
        .contentTop {
            display:none!important;
        }
        .content {;
            margin-left:0!important;
        }
        fieldset {
            position: relative;
            background: #EEE;
            border-radius: 0;
        }
        .form legend {
            font-size: 12px;
            line-height: 20px;
            background: #000;
            color: #fff;
            padding: 0 0 0;
            margin: 0;
        }
        legend:before{
            content:' ';
            padding:3px;
            float:left;
        }
        #content {
            padding:20px  5px  5px  5px;
        }
    </style>

    <table style="
    position: absolute;
    top:5px;
    left:5px;
    ">
        <tr>
            <td  style="background-color: #000; color:#fff;  padding:0 10px;  font-size:10px;  text-align:center">Nom</td>
            <td  style="background-color: #333; color:#fff;  padding:0 10px;  font-size:10px;  text-align:center">Talla</td>

            <?php if($dataDb['a_camiseta'] != '-') { ?>
                <td  style="background-color: #000; color:#fff;  padding:0 10px;  font-size:10px;  text-align:center">A. Nom</td>
                <td  style="background-color:#333; color:#fff;  padding:0 10px;  font-size:10px;  text-align:center">A. Talla</td>
            <?php } ?>

            <td  style="background-color:#000; color:#fff;  padding:0 10px;  font-size:10px;  text-align:center">€</td>


            <td  style="background-color:#FFCC00; color:#fff;  padding:0 10px;  font-size:10px;  text-align:center">N. sortida</td>
            <td  style="background-color: #000; color:#fff; padding:0 10px;  font-size:10px; text-align:center">Hora</td>
            <td  style="background-color:#FFCC00<?php // if($dataDb['check'] == '1') { echo '#0d9000;'; }else{ echo '#bc1e00;'; } ?>; color:#fff;  padding:0 10px;  font-size:10px;  text-align:center">Check</td>

        </tr>
        <tr>
            <td style="background-color:#FFCC00;  text-align:center; padding:5px 10px; vertical-align:middle; font-size:20px; color:#000; border-color:#FFF"><?php  echo $dataDb['nombre']; ?> <?php  echo $dataDb['apellido1']; ?></td>
            <td style="background-color:#FFE063;  text-align:center;  padding:5px 10px; vertical-align:middle; font-size:20px;  color:#000"><?php  echo $dataDb['camiseta']; ?></td>

            <?php if($dataDb['a_camiseta'] != '-') { ?>
                <td style="background-color:#FFCC00;  text-align:center; padding:5px 10px; vertical-align:middle; font-size:20px; color:#000; border-color:#FFF"><?php  echo $dataDb['a_nombre']; ?> <?php  echo $dataDb['a_apellido1']; ?></td>
                <td style="background-color:#FFE063;  text-align:center;  padding:5px 10px; vertical-align:middle; font-size:20px;  color:#000"><?php  echo $dataDb['a_camiseta']; ?></td>
            <?php } ?>

            <td style="background-color:#FFCC00;  text-align:center;  padding:5px 10px; vertical-align:middle; font-size:20px;  color:#000">

                    <?php

                    if($dataDb['acompanante'] == '1'){

                        $amount = 120.00;

                    }elseif( $dataDb['acompanante'] == '2'){

                        $amount = 65.00 + ( $dataDb['num_acompanante'] * 25.00);

                    }else {

                        $amount = 65.00;

                    }


                    echo  $amount;

                    ?>
            </td>

            <td style="background-color: #000;  text-align:center; padding:5px 10px; vertical-align:middle; font-size:20px; color:#fff; border-color:#FFF"><?php  echo $dataDb['numero_sortida']; ?></td>
            <td style="background-color: #FFCC00;  text-align:center;  padding:5px 10px; vertical-align:middle; font-size:20px;  color:#000"><?php  echo $dataDb['hora_sortida']; ?></td>
<?php

if($dataDb['check'] == '1') {

    echo '
    <td  style="
background-color: #0d9000;
font-size:30px;
line-height:20px;
position: relative;
padding:3px 7px;
color:#fff;
text-align:center;
    ">
    <span class=\'iconb\' data-icon=&#xe097;></span>
    </td>';

} else {

    echo '
    <td  style="
background-color: #bc1e00;
font-size:20px;
line-height:20px;
color:#fff;
padding:7px 7px;
text-align:center;
    ">
    <span class=\'iconb\' data-icon=&#xe095;></span>
    </td>';

}

?>


        </tr>
    </table>

<? } ?>


<?php /* if($this->formElementErrors($form->get('csrf'))){ ?>
        <div class="alert alert-info">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <p><?php echo $this->formElementErrors($form->get('csrf')); ?></p>
        </div>
    <?php } */?>

<?php if(isset($error)){ ?>
    <pre> <?php var_dump($error); ?>  </pre>
<?php }  ?>

<?php echo $this->qu_admin_messages(); ?>

<?php
//@Todo
if($action == 'config'){
    $span = 12;
} else{
    $span = 9;
}
?>

    <div class="form row-fluid">
        <div class="span<?php echo $span ?> fromIn">
            <?php

            $grid3         = array();
            $ckEditor      = array();
            $grid          = '';

            foreach ($form->getFieldsets() as $nameField => $FieldSets){

                $FieldGrid   = $FieldSets->getAttribute('span');
                $FieldClass  = $FieldSets->getAttribute('class');
                $Name        = $FieldSets->getName();

                if($FieldSets->getLabel()){
                    if($FieldGrid != 'span3'){

                        echo   '<fieldset class="formBlock '.$FieldClass.' '.$FieldSets->getName().'"><legend><span>';
                        echo   $FieldSets->getLabel();
                        echo   '</span></legend>';

                    } else{

                        $n  = $FieldSets->getName();
                        $grid  = '<fieldset class="formBlock '.$FieldClass.' '.$FieldSets->getName().'"><legend><span>';
                        $grid .= $FieldSets->getLabel();
                        $grid .= '</span></legend>';

                    }
                }

                $numField = count($FieldSets);
                $count    = 0;

                foreach ($FieldSets as $name =>$Element){
                    $count++;

                    if($Element->getAttribute('type') == 'select'){
                        $css = ' searchDrop';
                    }else{
                        $css   = false;
                    }

                    $elemClass = $Element->getAttribute('class');
                    $elemId    = $Element->getAttribute('id');
                    $elemGrid  = $Element->getAttribute('span');
                    $elemCk    = $Element->getAttribute('ck-editor');

                    if($elemCk){

                        echo ' <div class="row-fluid">';
                        echo   $this->formElement($Element);
                        echo   $this->formElementErrors($Element);
                        echo ' </div>';
                        $ckEditor[$elemId] = $elemCk;

                    }elseif($elemGrid == 'span3'){

                        $grid .= ' <div class="row-fluid"><div class="span3">';
                        $grid .= $Element->getLabel();
                        $grid .= ' </div><div class="span9'. $css .'">';
                        $grid .= $this->formElement($Element);
                        $grid .= ' </div><label generated="true" class="error">';
                        $grid .= $this->formElementErrors($Element);
                        $grid .= ' </label><div class="clear"></div></div>';


                    }else{

                        echo ' <div class="row-fluid"><div class="span3">';
                        echo   $Element->getLabel();
                        echo ' </div><div class="span9'. $css .'">';
                        echo   $this->formElement($Element);
                        echo ' <label generated="true" class="error">';
                        echo   $this->formElementErrors($Element);
                        echo ' </label></div><div class="clear"></div></div>';
                    }


                    if($numField  ==  $count)
                    {
                        if($elemGrid == 'span3')
                        {
                            $grid  .= ' </fieldset>';
                            $grid3[$n] =  $grid;
                        }
                        else
                        {
                            echo '</fieldset>';
                        }
                    }

                }
            }
            ?>

        </div>
        <div class="span3 fromIn">

            <?php  foreach($grid3 as $n){ echo $n;  } ?>

            <? /// FILE UPLOAD ///////////// ///////////// ?>

            <?php if($options->getDocuments()){  if($action == 'add'){ $id = 0; }  ?>
                <fieldset class="formBlock">
                    <legend>
                        <span>Multiple files uploader</span>
                    </legend>
                    <div class="row-fluid">
                        <div class="PluploadLoad"><?=$this->QuPluploadHelpLoad($id,$route,$options,$model)?></div>
                    </div>
                    <div class="row-fluid">
                        <div class="clear"></div>
                        <div id="uploader"></div>
                        <?php echo $this->QuPluploadHelp('uploader',$id,$options,$route,$model); ?>
                    </div>
                </fieldset>
            <? } ?>

            <? /// FILE UPLOAD ///////////// ///////////// ?>

        </div>
    </div>

<?php  echo $this->form()->closeTag($form) . PHP_EOL ?>

<?php

if(isset($ckEditor)){

    foreach($ckEditor as $id => $editor){


            $tools = array();


        if(isset($editor['height'])){
            $height = $editor['height'];
        }else{
            $height = 150;
        }

        $options = array(
            'width' => '100%',
            'height' => $height,
            'uiColor'=> '#FFFFFF',

        );

        $this->QuCKEditor($id,array_merge($options,$tools));

    }
}

?>