
<?php $this->placeholder('titol')->set(" <span class=\"iconb\" data-icon=\"&#xe047;\" style=\"margin-right:10px; font-size:11px\"></span> Register") ?>

<?php
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
?>

 <fieldset>
     <div class="widget fluid">
         <div class="whead"><h6><?=$this->placeholder('titol')?></h6><div class="clear"></div></div>




                     <?php foreach ($form as $element): ?>

                             <div class="formRow">

                                        <?php if (!$element instanceof Zend\Form\Element\Button): ?>


                                    <div class="grid3"><?=$this->formLabel($element)?></div>


                                                <?php endif ?>
                                                <?php if ($element instanceof Zend\Form\Element\Button): ?>


                                    <div class="grid12"><?php echo str_replace('<button','<button class="buttonL  bGreen  mt5 formSubmit"',$this->formButton($element)) ?></div>

                                                <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>

                                    <div class="grid9"><?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?></div>

                                                <?php else: ?>

                                    <div class="grid9"><?php echo $this->formInput($element) . $this->formElementErrors($element) ?></div>

                                                <?php endif ?>


                            <div class="clear"></div>
                            </div>

                    <?php endforeach ?>


</div>
</fieldset>



<?php echo $this->form()->closeTag() ?>
